Repository aremmell/libsir, pull requests merged in 2023-07, with the labels that each got.

#66 Flawfinder
  sirfilesystem.c
  sirhelpers.c
  sirhelpers.h
  sirinternal.c
  sirplatform.h
  sirtextstyle.c
  tests/tests.c
  tests/tests.h
Labels: enhancement

#85 Squelch spam
  .vscode/tasks.json
  Makefile
  docs/sources/TODO.md
  sirconfig.h
  sirhelpers.h
  sirinternal.c
  sirtypes.h
  tests/tests.c
  tests/tests.h
Labels: feature

#104 lstat before readlink (#44)
  sirfilesystem.c
  tests/tests.c
Labels: security

#118 Properly create `file.exists` (without explicitly running `make tests`)
  Makefile
Labels: bug

#117 Add OpenBSD support
  .gitignore
  README.md
  sirfilesystem.c
  sirfilesystem.h
  sirinternal.c
  sirplatform.h
Labels: enhancement

#158 A better sirfileid
  example/example.c
  sirfilecache.c
  sirhelpers.h
  sirtypes.h
  tests/tests.c
Labels: enhancement, security
