Repository aremmell/libsir, pull requests merged in 2023-12, with the labels that each got.

#362 add PlatformIO library manifest
  .reuse/dep5
  library.json
Labels: feature

#367 Use hexadecimal for printing numeric thread IDs on NetBSD; misc. CI updates
  .gitlab-ci.yml
  .gitlab-ci/funcheck/Dockerfile
  README.md
  docs/config_8h.html
  docs/config_8h.js
  docs/config_8h_source.html
  docs/errors_8h_source.html
  docs/globals.html
  docs/globals_defs.html
  docs/helpers_8h_source.html
  docs/index.html
  docs/maps_8h_source.html
  docs/navtreedata.js
  docs/navtreeindex0.js
  docs/navtreeindex1.js
  docs/platform_8h_source.html
  docs/search/all_12.js
  docs/search/defines_8.js
  docs/sir_8h_source.html
  docs/sir_8hh_source.html
  docs/textstyle_8h_source.html
  docs/types_8h_source.html
  include/sir/config.h
  include/sir/platform.h
  src/sirinternal.c
  tests/tests.c
Labels: enhancement, ci/cd

#368 Cosmetic alignment
  tests/tests.c
Labels: cleanup

#369 Update README; new CI rules …
  .gitlab-ci.yml
  README.md
  docs/index.html
  tests/tests.c
Labels: ci/cd, cleanup, documentation

#373 Annotate `build-aux/install-sh` to pass ShellCheck
  LICENSES/X11.txt
  build-aux/install-sh
Labels: low-priority, cleanup

#371 Add local `strcasestr` implementation
  LICENSES/BSD-3-Clause.txt
  docs/impl_8h_source.html
  docs/platform_8h_source.html
  include/sir/impl.h
  include/sir/platform.h
  src/sirerrors.c
Labels: portability

#372 Explicitly enable C++ two-phase name lookup in MSVC
  .gitlab-ci.yml
Labels: ci/cd

#375 update version.h for 2.2.5-dev
  .lint.sh
  autoformat.sh
  include/sir/version.h
Labels: low-priority, cleanup
