Repository aremmell/libsir, pull requests merged in 2023-09, with the labels that each got.

#255 remove errors.h dependency on helpers.h
  Makefile
  include/sir/errors.h
  include/sir/helpers.h
  sirplatform.mk
  src/sirerrors.c
  tests/tests.c
Labels: enhancement

#267 fix logic error in _sir_andeql, rename to _sir_eqland
  include/sir/helpers.h
  src/sirerrors.c
  src/sirinternal.c
  src/sirtextstyle.c
  tests/tests.c
Labels: bug

#262 Use arc4random on more platforms in test harness
  tests/tests.c
Labels: enhancement

#265 don't fstat log files on every write, only every n
  include/sir/config.h
  include/sir/types.h
  src/sirfilecache.c
Labels: enhancement

#268 On Windows, use native Win32 API for file I/O
  include/sir/filecache.h
  include/sir/filesystem.h
  include/sir/helpers.h
  include/sir/types.h
  src/sirfilecache.c
  src/sirfilesystem.c
  src/sirhelpers.c
  tests/tests.c
Labels: enhancement

#269 Require AVX tag on NVIDIA CI job
  .gitlab-ci.yml
Labels: ci/cd

#263 Thread pool fixes
  include/sir/threadpool.h
  src/sirthreadpool.c
  tests/tests.c
Labels: bug, cleanup

#270 Update OrangeC to 6.0.71.10
  .gitlab-ci.yml
  .gitlab-ci/orangec/Dockerfile
  README.md
  include/sir/platform_orangec.h
  include/sir/types.h
  src/sirinternal.c
Labels: ci/cd, cleanup

#264 Return false if text styles fail to reset
  src/sirtextstyle.c
Labels: cleanup

#261 Coverity: Fix for unchecked return values
  example/example.c
  tests/tests.c
  tests/tests.h
Labels: cleanup

#271 Only re-format time stamp string if the numeric time has changed
  src/sirinternal.c
Labels: enhancement

#273 macroize _sir_valid* functions in order to capture source info
  include/sir/helpers.h
  src/sirhelpers.c
  tests/tests.c
Labels: enhancement

#274 Check for `log/*` remnants after running `sirtests`
  .gitlab-ci.yml
Labels: ci/cd

#275 reset tls data on cleanup; only copy tid/name if set
  include/sir/internal.h
  src/sirinternal.c
Labels: bug

#276 _sir_validstrnofail does not need to call __sir_validstr
  include/sir/helpers.h
Labels: enhancement

#279 add .user files for sirtests and sirexample, ignore the rest
  .gitignore
  msvs/sirexample.vcxproj.user
  msvs/sirtests.vcxproj.user
Labels: enhancement, cleanup

#280 Reset TLS error info (closes #260)
  include/sir/errors.h
  src/sirerrors.c
  src/sirinternal.c
Labels: bug, cleanup

#287 Add support for building as WebAssembly with Emscripten for Node.js
  README.md
  include/sir/platform.h
  sirplatform.mk
  src/sirfilesystem.c
  src/sirinternal.c
  tests/tests.c
Labels: portability

#294 add `sir_isinitialized` convenience function
  include/sir.h
  include/sir/internal.h
  src/sir.c
  src/sirinternal.c
  tests/tests.c
  tests/tests.h
Labels: enhancement

#297 update readme
  README.md
Labels: cleanup

#302 Don't squelch repeating messages that are sent to differing levels
  include/sir/types.h
  src/sirinternal.c
  tests/tests.c
Labels: bug

#303 Improve test coverage
  example/example.c
  include/sir.hh
  include/sir/filecache.h
  include/sir/helpers.h
  src/sirfilecache.c
  src/sirplugins.c
  tests/tests++.cc
Labels: enhancement, ci/cd

#301 Add sir_geterrorinfo to obtain extended information about an error
  README.md
  bindings/python/sir.i
  include/sir.h
  include/sir.hh
  include/sir/errors.h
  include/sir/types.h
  src/sir.c
  src/sirerrors.c
  tests/tests++.cc
  tests/tests++.hh
  tests/tests.c
Labels: enhancement, feature

#298 add CODEOWNERS (OSS score card demands it)
  .gitattributes
  .github/CODEOWNERS
Labels: enhancement, cleanup

#305 Add support for Windows Event Viewer
  include/sir/platform.h
  include/sir/platform_embarcadero.h
  include/sir/wineventlog.h
  msvs/compile_man.ps1
  msvs/sir_wineventlog.man
  msvs/util.ps1
  src/sirerrors.c
  src/sirinternal.c
  tests/tests.c
  tests/tests.h
Labels: feature

#311 refactor _sir_getchar
  src/sirhelpers.c
Labels: enhancement, cleanup

#310 remove newlines that got past me when i refactored for sirtests++
  tests/tests.c
Labels: cleanup

#312 Fix: file name splitting with `./` prefix
  src/sirfilecache.c
  tests/tests.c
Labels: bug

#313 CI: Add Clang-CL jobs
  .gitignore
  .gitlab-ci.yml
  .lint.sh
  Makefile
  README.md
  docs/index.html
  docs/navtreeindex1.js
  docs/platform__orangec_8h_source.html
  docs/tests_8h_source.html
  include/sir/platform_orangec.h
Labels: enhancement, ci/cd, cleanup

#314 try to appease coverity by rearranging boundary checks
  src/sirfilecache.c
Labels: cleanup

#319 Add CFI (Control Flow Integrity) CI jobs
  .gitlab-ci.yml
Labels: ci/cd

#316 Update Semgrep (GitLab SAST rules) CI job.
  .gitlab-ci.yml
Labels: bug, ci/cd

#315 Add test for rolling "`./`"-prefixed files with no extension.
  sir.code-workspace
  tests/tests.c
  tests/tests.h
Labels: enhancement, cleanup

#320 Minor updates to CI scripts
  .editorconfig
  .gitlab-ci.yml
  .gitlab-ci/anaconda/Dockerfile
  .gitlab-ci/ao64/Dockerfile
  .gitlab-ci/base/Dockerfile
  .gitlab-ci/ch/Dockerfile
  .gitlab-ci/circle/Dockerfile
  .gitlab-ci/dmd/Dockerfile
  .gitlab-ci/embarcadero/Dockerfile
  .gitlab-ci/emscripten/Dockerfile
  .gitlab-ci/intel/Dockerfile
  .gitlab-ci/kefir/Dockerfile
  .gitlab-ci/llvm-mingw/Dockerfile
  .gitlab-ci/msvc/Dockerfile
  .gitlab-ci/msvc/install.sh
  .gitlab-ci/ndk/Dockerfile
  .gitlab-ci/nvhpc/Dockerfile
  .gitlab-ci/oracle/Dockerfile
  .gitlab-ci/orangec/Dockerfile
  .gitlab-ci/pvs/Dockerfile
  .gitlab-ci/scripts/all.sh
  .gitlab-ci/scripts/build.sh
  .gitlab-ci/scripts/push.sh
  .gitlab-ci/style/Dockerfile
  .gitlab-ci/uclibc-ng/Dockerfile
  .lint.sh
  README.md
  tests/tests.c
Labels: ci/cd
