Repository aremmell/libsir, pull requests merged in 2024-01, with the labels that each got.

#377 Update for Emscripten
  .gitlab-ci/anaconda/Dockerfile
  .gitlab-ci/emscripten/Dockerfile
  README.md
Labels: ci/cd, cleanup

#376 Tweaks based on cppcheck linter warnings
  .lint.sh
  autoformat.sh
  include/sir/threadpool.h
  src/sirfilecache.c
  src/sirfilesystem.c
  src/sirhelpers.c
  src/sirinternal.c
  src/sirplugins.c
  tests/tests.c
Labels: cleanup

#378 Exclude build
  autoformat.sh
Labels: cleanup

#379 Update tested compiler versions
  README.md
Labels: documentation

#380 Fix spelling in comment: `Souce code` -> `Source code`
  docs/res/style.css
Labels: cleanup

#381 Updates for CI (Nodejs v21.6.0, DMD ImportC v2.106.1...)
  .gitlab-ci/anaconda/Dockerfile
  .gitlab-ci/ao64/Dockerfile
  .gitlab-ci/base/Dockerfile
  .gitlab-ci/emscripten/Dockerfile
  .gitlab-ci/intel/Dockerfile
  .gitlab-ci/pvs/Dockerfile
  .lint.sh
  README.md
Labels: enhancement, ci/cd, documentation

#382 Update Coverity submission script to work with wget2
  .coverity.sh
Labels: bug

#383 Trim trailing whitespace
  msvs/README.md
Labels: cleanup, documentation

#384 Simplify and update syntax for Kefir build in Dockerfile
  .gitlab-ci/kefir/Dockerfile
Labels: ci/cd, cleanup

#385 Bump tested Node version; minor CI builder tweaks
  .gitlab-ci/anaconda/Dockerfile
  .gitlab-ci/ao64/Dockerfile
  .gitlab-ci/ch/Dockerfile
  .gitlab-ci/chamois-compcert/Dockerfile
  .gitlab-ci/circle/Dockerfile
  .gitlab-ci/dmd/Dockerfile
  .gitlab-ci/embarcadero/Dockerfile
  .gitlab-ci/embarcadero23/Dockerfile
  .gitlab-ci/emscripten/Dockerfile
  .gitlab-ci/intel/Dockerfile
  .gitlab-ci/kefir/Dockerfile
  .gitlab-ci/msvc/Dockerfile
  .gitlab-ci/ndk/Dockerfile
  .gitlab-ci/nvhpc/Dockerfile
  .gitlab-ci/obggcc/Dockerfile
  .gitlab-ci/oracle/Dockerfile
  .gitlab-ci/orangec/Dockerfile
  .gitlab-ci/pvs/Dockerfile
  .gitlab-ci/scripts/build.sh
  .gitlab-ci/uclibc-ng/Dockerfile
  README.md
Labels: ci/cd, documentation
