Repository aremmell/libsir, pull requests merged in 2024-02, with the labels that each got.

#393 Special filesystem handling for PASE
  README.md
  autoformat.sh
  docs/filesystem_8h_source.html
  docs/index.html
  docs/navtreeindex1.js
  docs/platform_8h_source.html
  docs/tests_8h_source.html
  include/sir/filesystem.h
  include/sir/platform.h
  sirplatform.mk
  src/sirfilesystem.c
  tests/tests.c
Labels: portability

#394 Always build with `-D_THREAD_SAFE` on OS/400 and AIX
  sirplatform.mk
Labels: portability

#397 Add AVX tag to PVS-Studio job
  .gitlab-ci.yml
Labels: bug, ci/cd

#398 Update tested IBM XL compiler versions
  README.md
Labels: documentation

#399 Minor build tweaks for PASE for IBM i (OS/400)
  README.md
  docs/index.html
  docs/navtreeindex1.js
  sirplatform.mk
Labels: portability, cleanup

#400 mcmb: Remove unused and debugging functionality
  utils/mcmb/mcmb.1
  utils/mcmb/mcmb.c
Labels: enhancement, cleanup
